add check for adeptutils in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -820,6 +820,9 @@ LIBTOOL
 CALLPATH_LIBS
 CALLPATH_LDFLAGS
 CALLPATH_CFLAGS
+ADEPTUTILS_LIBS
+ADEPTUTILS_LDFLAGS
+ADEPTUTILS_CFLAGS
 MPI_CLDFLAGS
 MPI_CFLAGS
 MPICC
@@ -932,6 +935,7 @@ ac_subst_files=''
 ac_user_opts='
 enable_option_checking
 enable_dependency_tracking
+with_adept_utils
 with_callpath
 enable_shared
 enable_static
@@ -1592,6 +1596,7 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-adept-utils=PATH Specify adept-utils path
   --with-callpath=PATH    Specify libcallpath path
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -4909,6 +4914,124 @@ _ACEOF
 
 
 
+  _x_ac_adeptutils_dirs="/usr /opt/freeware"
+  _x_ac_adeptutils_libs="lib64 lib"
+
+
+# Check whether --with-adept-utils was given.
+if test "${with_adept_utils+set}" = set; then
+  withval=$with_adept_utils; _x_ac_adeptutils_dirs="$withval"
+     with_adeptutils=yes
+else
+  _x_ac_adeptutils_dirs=no
+     with_adeptutils=no
+
+fi
+
+
+  if test "x$_x_ac_adeptutils_dirs" = xno ; then
+    # user explicitly wants to disable adept utils support
+    ADEPTUTILS_CFLAGS=""
+    ADEPTUTILS_LDFLAGS=""
+    ADEPTUTILS_LIBS=""
+    # TODO: would be nice to print some message here to record in the config log
+  else
+    # user wants adept utils enabled, so let's define it in the source code
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBADEPTUTILS 1
+_ACEOF
+
+
+    # now let's locate the install location
+    found=no
+
+    # check for adept-utils in a system default location if:
+    #   --with-adept-utils or --without-adept-utils is not specified
+    #   --with-adept-utils=yes is specified
+    #   --with-adept-utils is specified
+    if test "$with_adeptutils" = check || \
+       test "x$_x_ac_adeptutils_dirs" = xyes || \
+       test "x$_x_ac_adeptutils_dirs" = "x" ; then
+#      AC_CHECK_LIB([adept_utils], [GCS_Comm_split])
+
+      # if we found it, set the build flags
+      if test "$ac_cv_lib_adeptutils_GCS_Comm_split" = yes; then
+        found=yes
+        ADEPTUTILS_CFLAGS=""
+        ADEPTUTILS_LDFLAGS=""
+        ADEPTUTILS_LIBS="-ladept_cutils -ladept_timing -ladept_utils"
+      fi
+    fi
+
+    # if we have not already found it, check the adeptutils_dirs
+    # we look for a reasonable number of headers to be sure we found it
+    if test "$found" = no; then
+      { $as_echo "$as_me:$LINENO: checking for adept-utils installation" >&5
+$as_echo_n "checking for adept-utils installation... " >&6; }
+if test "${x_ac_cv_adeptutils_dir+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+
+          for d in $_x_ac_adeptutils_dirs; do
+            test -d "$d" || continue
+            test -d "$d/include" || continue
+            test -f "$d/include/io_utils.h" || continue
+            test -f "$d/include/link_utils.h" || continue
+            test -f "$d/include/matrix_utils.h" || continue
+            test -f "$d/include/mpi_utils.h" || continue
+            test -f "$d/include/string_utils.h" || continue
+            for bit in $_x_ac_adeptutils_libs; do
+              test -d "$d/$bit" || continue
+
+# TODO: replace line below with link test
+              x_ac_cv_adeptutils_dir=$d
+#              _x_ac_adeptutils_libs_save="$LIBS"
+#              LIBS="-L$d/$bit -ladept_utils $LIBS $MPI_CLDFLAGS"
+#              AC_LINK_IFELSE(
+#                AC_LANG_CALL([], [ADEPTUTILS_Comm_split]),
+#                AS_VAR_SET([x_ac_cv_adeptutils_dir], [$d]))
+#              LIBS="$_x_ac_adeptutils_libs_save"
+#              test -n "$x_ac_cv_adeptutils_dir" && break
+            done
+            test -n "$x_ac_cv_adeptutils_dir" && break
+          done
+
+fi
+{ $as_echo "$as_me:$LINENO: result: $x_ac_cv_adeptutils_dir" >&5
+$as_echo "$x_ac_cv_adeptutils_dir" >&6; }
+
+      # if we found it, set the build flags
+      if test -n "$x_ac_cv_adeptutils_dir"; then
+        found=yes
+        ADEPTUTILS_CFLAGS="-I$x_ac_cv_adeptutils_dir/include"
+        ADEPTUTILS_LDFLAGS="-L$x_ac_cv_adeptutils_dir/$bit"
+        ADEPTUTILS_LIBS="-ladept_cutils -ladept_timing -ladept_utils"
+      fi
+    fi
+
+    # if we failed to find adept utils, throw an error
+    if test "$found" = no ; then
+      { { $as_echo "$as_me:$LINENO: error: unable to locate adept utils installation" >&5
+$as_echo "$as_me: error: unable to locate adept utils installation" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+  fi
+
+  # adept utils is required
+  if test "x$ADEPTUTILS_LIBS" = "x" ; then
+    { { $as_echo "$as_me:$LINENO: error: unable to locate adept-utils installation" >&5
+$as_echo "$as_me: error: unable to locate adept-utils installation" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  # propogate the build flags to our makefiles
+
+
+
+
+
+
   _x_ac_callpath_dirs="/usr /opt/freeware"
   _x_ac_callpath_libs="lib64 lib"
 
@@ -5726,13 +5849,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5729: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5852: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5732: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5855: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5735: output\"" >&5)
+  (eval echo "\"\$as_me:5858: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6938,7 +7061,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6941 "configure"' > conftest.$ac_ext
+  echo '#line 7064 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9533,11 +9656,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9536: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9659: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9540: \$? = $ac_status" >&5
+   echo "$as_me:9663: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9872,11 +9995,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9875: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9879: \$? = $ac_status" >&5
+   echo "$as_me:10002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9977,11 +10100,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10103: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9984: \$? = $ac_status" >&5
+   echo "$as_me:10107: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10032,11 +10155,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10035: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10158: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10039: \$? = $ac_status" >&5
+   echo "$as_me:10162: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12835,7 +12958,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12838 "configure"
+#line 12961 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12931,7 +13054,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12934 "configure"
+#line 13057 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14951,11 +15074,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14954: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15077: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14958: \$? = $ac_status" >&5
+   echo "$as_me:15081: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15050,11 +15173,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15053: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15176: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15057: \$? = $ac_status" >&5
+   echo "$as_me:15180: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15102,11 +15225,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15105: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15228: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15109: \$? = $ac_status" >&5
+   echo "$as_me:15232: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
